# Generated by Django 5.1.3 on 2025-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='escuro', max_length=10)),
                ('cor_mensagem_user', models.CharField(default='#007BFF', max_length=7)),
                ('cor_mensagem_bot', models.CharField(default='#444', max_length=7)),
                ('tamanho_fonte', models.IntegerField(default=14)),
                ('avatar_bot', models.BooleanField(default=True)),
                ('modelo_ia', models.CharField(default='3b', max_length=10)),
                ('temperatura', models.FloatField(default=0.7)),
                ('notificacoes_som', models.BooleanField(default=True)),
                ('atalhos_ativos', models.BooleanField(default=True)),
            ],
        ),
    ]
